name: 'Execute tests'
description: 'Execute tests on python'
inputs:
  doppler-token-tests:
    description: 'Doppler token for tests'
    required: true
  python-version:
    description: 'Python version'
    required: true
  pypi-user:
    description: 'PyPi user'
    required: true
  pypi-password:
    description: 'PyPi password'
    required: true
  all_extras:
    description: 'Install All Extras'
    required: false
    default: 'false'
  custom-test-directories:
    description: 'Custom test directories (comma-separated for multiple)'
    required: false
    default: '' # Se vazio, utiliza o padrão único

runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install host dependencies
      shell: bash
      run: sudo apt update && sudo apt-get install -y locales locales-all libcurl4-openssl-dev libssl-dev

    - name: Cache pip
      uses: actions/cache@v3
      with:
        path: /opt/hostedtoolcache/Python/${{ inputs.python-version }}/x64/
        key: python${{ inputs.python-version }}-${{ runner.os }}-poetry-${{ hashFiles('poetry.lock') }}

    - name: Install Dependencies
      env:
        PYPI_USER: ${{ inputs.pypi-user }}
        PYPI_PASSWORD: ${{ inputs.pypi-password }}
      shell: bash
      run: |
        pip install poetry
        poetry config virtualenvs.create false
        poetry config http-basic.zapay-pypi $PYPI_USER $PYPI_PASSWORD
        if [ "${{ inputs.all_extras }}" = "true" ]; then
          poetry install --all-extras --no-interaction --no-ansi -vvv
        else
          poetry install --no-interaction --no-ansi -vvv
        fi

    - name: Install Doppler
      shell: bash
      run: |
        echo "Installing Doppler..."
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl gnupg
        curl -sLf --retry 3 --tlsv1.2 --proto "=https" 'https://packages.doppler.com/public/cli/gpg.DE2A7741A397C129.key' | sudo gpg --dearmor -o /usr/share/keyrings/doppler-archive-keyring.gpg
        echo "deb [signed-by=/usr/share/keyrings/doppler-archive-keyring.gpg] https://packages.doppler.com/public/cli/deb/debian any-version main" | sudo tee /etc/apt/sources.list.d/doppler-cli.list
        sudo apt-get update && sudo apt-get install doppler

    - name: Tests
      env:
        DOPPLER_TOKEN: ${{ inputs.doppler-token-tests }}
      shell: bash
      run: |
        echo "Preparing to run tests..."
        
        # Verifica e converte os diretórios de teste em uma lista
        if [ -z "${{ inputs.custom-test-directories }}" ]; then
          TEST_DIRS=("src") # Diretório padrão
        else
          IFS=',' read -r -a TEST_DIRS <<< "${{ inputs.custom-test-directories }}" # Divide múltiplos diretórios
        fi

        echo "Running tests in directories: ${TEST_DIRS[*]}"
        
        # Executa os testes em cada diretório
        for TEST_DIR in "${TEST_DIRS[@]}"
        do
          echo "Running tests for $TEST_DIR..."
          doppler run -- pytest $TEST_DIR --cov=$TEST_DIR --cov-report xml:coverage.xml || exit 1
        done

    - name: Upload coverage to the next step
      uses: actions/upload-artifact@v3
      with:
        name: coverage-${{ github.run_id }}
        path: coverage.xml
